# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/ogarcia138/aqsis;/home/ogarcia138")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "main;docs;examples;shaders;plugins;development;Unspecified")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "Include and library files for software development")
set(CPACK_COMPONENT_DOCS_DESCRIPTION "User manual and guides (.pdf)")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Example files (.rib)")
set(CPACK_COMPONENT_EXAMPLES_GROUP "content")
set(CPACK_COMPONENT_GROUP_CONTENT_DESCRIPTION "Examples and shader source files")
set(CPACK_COMPONENT_MAIN_DESCRIPTION "Rendering application and essential files only")
set(CPACK_COMPONENT_MAIN_REQUIRED "TRUE")
set(CPACK_COMPONENT_PLUGINS_DESCRIPTION "Plugins for external applications")
set(CPACK_COMPONENT_SHADERS_DESCRIPTION "Generic shader source files (.sl)")
set(CPACK_COMPONENT_SHADERS_GROUP "content")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "aqsis_all built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES ".*/\\.git/")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/ogarcia138/aqsis;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/ogarcia138/aqsis/cmake/modules;/home/ogarcia138/aqsis/cmake")
set(CPACK_NSIS_DISPLAY_NAME "Aqsis")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Aqsis")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/ogarcia138/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/ogarcia138/aqsis/README")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Aqsis Renderer")
set(CPACK_PACKAGE_FILE_NAME "aqsis-1.8.4")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Aqsis")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Aqsis")
set(CPACK_PACKAGE_NAME "Aqsis")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Aqsis Team")
set(CPACK_PACKAGE_VERSION "1.8.4")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "8")
set(CPACK_PACKAGE_VERSION_PATCH "4")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/ogarcia138/aqsis/COPYING")
set(CPACK_RESOURCE_FILE_README "/home/ogarcia138/aqsis/README")
set(CPACK_RESOURCE_FILE_WELCOME "/home/ogarcia138/aqsis/README")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES ".*/\\.git/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/ogarcia138/aqsis;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/ogarcia138/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "aqsis-1.8.4")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/ogarcia138/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
