# This file contains exported build targets, for use by external projects via
# the cmake find_package() command in "Config mode".

set(Aqsis_VERSION_MAJOR 1)
set(Aqsis_VERSION_MINOR 8)
set(Aqsis_VERSION_BUILD 4)

set(Aqsis_INCLUDE_DIRECTORIES
	/home/ogarcia138/aqsis_build/include
	/home/ogarcia138/aqsis/include
	)

# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS aqsis_core aqsis_math aqsis_shadervm aqsis_tex aqsis_util aqsis_riutil)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target aqsis_core
add_library(aqsis_core SHARED IMPORTED)

set_target_properties(aqsis_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "aqsis_math;aqsis_riutil;aqsis_shadervm;aqsis_tex;aqsis_util;aqsis_riutil;/usr/lib/x86_64-linux-gnu/libtiff.so;Boost::thread;Boost::timer"
)

# Create imported target aqsis_math
add_library(aqsis_math SHARED IMPORTED)

# Create imported target aqsis_shadervm
add_library(aqsis_shadervm SHARED IMPORTED)

set_target_properties(aqsis_shadervm PROPERTIES
  INTERFACE_LINK_LIBRARIES "aqsis_math;aqsis_util;aqsis_tex;Boost::regex"
)

# Create imported target aqsis_tex
add_library(aqsis_tex SHARED IMPORTED)

set_target_properties(aqsis_tex PROPERTIES
  INTERFACE_LINK_LIBRARIES "aqsis_math;aqsis_util;/usr/lib/x86_64-linux-gnu/libtiff.so;/usr/lib/x86_64-linux-gnu/libtiffxx.so;/usr/lib/x86_64-linux-gnu/libpng.so;/usr/lib/x86_64-linux-gnu/libOpenEXR.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libImath.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libz.so"
)

# Create imported target aqsis_util
add_library(aqsis_util SHARED IMPORTED)

set_target_properties(aqsis_util PROPERTIES
  INTERFACE_LINK_LIBRARIES "Boost::filesystem;dl;Boost::system"
)

# Create imported target aqsis_riutil
add_library(aqsis_riutil SHARED IMPORTED)

set_target_properties(aqsis_riutil PROPERTIES
  INTERFACE_LINK_LIBRARIES "aqsis_util;Boost::iostreams"
)

# Import target "aqsis_core" for configuration "Release"
set_property(TARGET aqsis_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/core/libaqsis_core.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_core.so.1"
  )

# Import target "aqsis_math" for configuration "Release"
set_property(TARGET aqsis_math APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_math PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/math/libaqsis_math.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_math.so.1"
  )

# Import target "aqsis_shadervm" for configuration "Release"
set_property(TARGET aqsis_shadervm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_shadervm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/shadervm/libaqsis_shadervm.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_shadervm.so.1"
  )

# Import target "aqsis_tex" for configuration "Release"
set_property(TARGET aqsis_tex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_tex PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/tex/libaqsis_tex.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_tex.so.1"
  )

# Import target "aqsis_util" for configuration "Release"
set_property(TARGET aqsis_util APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_util PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/util/libaqsis_util.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_util.so.1"
  )

# Import target "aqsis_riutil" for configuration "Release"
set_property(TARGET aqsis_riutil APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aqsis_riutil PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/ogarcia138/aqsis_build/libs/riutil/libaqsis_riutil.so.1.8"
  IMPORTED_SONAME_RELEASE "libaqsis_riutil.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
